[package]
name = "maryada"
version = "0.1.2"
edition = "2024"
rust-version = "1.87"
description = "No-std binary64 real interval arithmetic conforming to IEEE 1788.1"
documentation = "https://docs.rs/maryada"
readme = "README.md"
repository = "https://github.com/denehoffman/maryada"
license = "MIT OR Apache-2.0"
keywords = ["interval", "arithmetic", "ieee-1788", "numerics", "no-std"]
categories = ["mathematics", "no-std", "science"]

[dependencies]
libm = { version = "=0.2.16", default-features = false }
num-complex = { version = "0.4.6", default-features = false, optional = true }

[features]
default = []
complex = []
num-complex = ["complex", "dep:num-complex"]
